# Generated by Django 3.2.9 on 2022-02-07 08:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(10)])),
                ('picture', models.ImageField(upload_to='articles')),
                ('author_name', models.CharField(blank=True, max_length=20)),
                ('article_text', models.TextField(validators=[django.core.validators.MinLengthValidator(20)])),
                ('created', models.DateField(auto_now_add=True)),
                ('last_modified', models.DateField(auto_now=True)),
            ],
        ),
    ]
