# Generated by Django 3.2.9 on 2022-04-02 11:16

from django.db import migrations
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_article_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_text',
            field=django_quill.fields.QuillField(),
        ),
    ]
