# Generated by Django 3.2.9 on 2022-02-07 08:48

from django.db import migrations, models
import django.db.models.deletion
import legal_map.legal_help.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('legal_auth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('first_name', models.CharField(blank=True, max_length=20, validators=[legal_map.legal_help.validators.validate_name])),
                ('last_name', models.CharField(blank=True, max_length=20, validators=[legal_map.legal_help.validators.validate_name])),
                ('job_title', models.CharField(blank=True, max_length=40)),
                ('company_name', models.CharField(blank=True, max_length=40, validators=[legal_map.legal_help.validators.validate_name])),
                ('is_complete', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='legal_auth.legaluser')),
            ],
        ),
    ]
