# Generated by Django 3.2.9 on 2022-02-07 08:48

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import legal_map.legal_help.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MainArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, upload_to='areas')),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(3), legal_map.legal_help.validators.validate_name])),
                ('picture', models.ImageField(blank=True, upload_to='legal')),
                ('address', models.CharField(blank=True, max_length=200)),
                ('phone_number', models.CharField(max_length=20)),
                ('expertise', models.TextField(blank=True)),
                ('website', models.URLField(blank=True)),
                ('areas', models.ManyToManyField(blank=True, to='legal_help.MainArea')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
